### ISSUE TITLE
Subaru and Oriel Sites template reviews

### ISSUE THREAD

**Issue by OsteenM** [EdgeTech1/EDGE-TECH#1]
My people lets first drop the templates we think we should go ahead with

**Comment by derrosilee** [comment]
Si will be doing the Subaru like design

**Comment by OsteenM** [comment]
Yeah bruhv

**Comment by derrosilee** [comment]
> 
> 
> Yeah bruhv

**Comment by derrosilee** [comment]
hehehe una ni asign nn wewe

**Comment by OsteenM** [comment]
Come up with a similar design we see

**Comment by derrosilee** [comment]
sawa mkubwa

**Comment by derrosilee** [comment]
Ngumbau ako wapi

**Comment by OsteenM** [comment]
Ako missing for some reason 😂😂

**Comment by OsteenM** [comment]
Btw nafanya python....Ni very interesting...kuliko ata JS

**Comment by derrosilee** [comment]
😂😂yea alafu syntax yake ni Kama tu English

**Comment by kelvin-ngumbao** [comment]
> Ako missing for some reason 😂😂

😂😂😂😂
